### ISSUE TITLE
Overlay shortcuts

### ISSUE THREAD

**Issue by gczark** [ppkantorski/Ultrahand-Overlay#199]
Hello, is it possible to pull some commands from an overlay then merge them with the others.
For example, I only want to see the slider from `Master Volume` and the toggle from `Fizeau`.

Out of topic, how can I modify the slider in `Master Volume` to have increments of 0.20?

**Comment by ppkantorski** [comment]
You can create a trackbar slider in an Ultrahand package to control the brightness, but I don't think i've added volume.  However I can if it is desired.  As for the other Fizeau settings, I will not be adding the ability to control color and contrast.  Those can be controlled via Fizeau pretty easily.

**Comment by ppkantorski** [comment]
Actually master volume may be a bit trickier than I thought.  I couldn't get it working with libnx's current methods, and there isn't much to go off of.  I may have to just look into it more later.  Hopefully I've addressed your question, but since there isn't an issue being raised I am going to be closing this issue.  If I ever figure it out / get it working, I'll add it in.
