### ISSUE TITLE
Menu getting stuck

### ISSUE THREAD

**Issue by monstrosities** [ppkantorski/Ultrahand-Overlay#5]
Hello,

First of all thanks for fixing the other issues I reported. One thing I've been encountering at random is that the menu gets stuck on a certain page, for example sometimes I can't get back to the main overlays menu from the packages menu. Since it doesn't happen on every occasion I'm not sure what the cause of this is, is this a known issue?

For reference I am using Atmosphere 1.5.4 and firmware 16.0.3.

**Comment by ppkantorski** [comment]
So far I have only been able to trigger the bug you describe when replacing `ovlmenu.ovl` while the Switch is running live.  It used to trigger in different cases in the past.  After the file has been replaced and main menu has been exited and returned to a few times (or system rebooted) I haven't seen the issue re-appear.

Can you describe what happens leading up to it getting stuck?  Whenever it does get stuck, it's because it keeps track of its position within menus and (for some reason) "thinks" its in a different menu for handling input.  It is a known issue according to one other person under very certain test cases for them, but it is one that I've yet to be able to reproduce.  Also, please describe what your `key_combo` is (if you modified it or not).

**Comment by monstrosities** [comment]
I am just using overlays normally and from time to time this seemingly occurs at random so it's difficult to describe what happens leading up to it getting stuck, if I can gather any further information I will provide it. So far I haven't changed from the default for the values you mentioned such as `key_combo`

**Comment by ppkantorski** [comment]
there could be a potential issue if the key combo consists of ```KEY_DRIGHT``` or ```KEY_DLEFT``` (which are the  known buttons to swap between overlay and package menus).  I'll have to investigate it further.  I forgot, was the Tesla original combo now L + DRight + R3?

**Comment by ppkantorski** [comment]
Ok i figured out how to trigger the issue.  If I hold down ZL and click B, it seems to resort back to the default back which is ```tsl::goBack();```, causing issues at times.  Now that ive at least witnessed the bug, I believe I can go about fixing it.

**Comment by ppkantorski** [comment]
actually this might just be the result of my modifications trying to fix the code... hmm.  i will make a 1.1.8 pre-release to test some of my changes.  try it out and let me know if the issue persists.

**Comment by monstrosities** [comment]
I still experience the issue with 1.1.8.

**Comment by ppkantorski** [comment]
just curious, what overlays are you using that leads up to this issue?  how exactly do you get it to repeat itself?

**Comment by ppkantorski** [comment]
I've changed the overlay booleans to static types.  This could potentially fix the issue you're having.  Been pushing a good amount of updates, but I'll wait until 1.1.9 has some more features before I drop a pre-release.

**Comment by ppkantorski** [comment]
Try v1.1.9.  I made some changes that could affect the bug you mentioned.  Because it was difficult to reproduce your bug for me, I cannot confirm if my implementation corrections have fixed the issue or not, but the way it was coded before may have indeed caused issues without static variables.

**Comment by ppkantorski** [comment]
i fixed a number of other reasons why this issue could happen, including touch selection.   You can still scroll with touch commands, but i removed the ability to go back by touching back and enter an item by tapping on it.  When nothing is selected and back is applied, the menu can get confused at times.   I would like to say that the bug is fixed now after all of these modifications.  I will leave this open for a few more days before closing it.  if the issue reappears do post it again and we can address it further.

**Comment by monstrosities** [comment]
Thanks for the updates, it seems to be fixed in the latest version so I'll go ahead and close this.
